site_name: Python Training for Devops.
nav:
  - Home: index.md
  - Python Syntax: syntax.md
  - Memory Management: mem.md
  - Global Interpreter Lock: gil.md
  - Object Oriented Programming: oops.md
  - Basic Tooling for Python: tooling.md
  - Best Practices for programming and python: best_practices.md
  - Creating a CLI application: cliapp.md
  - Logging in application: logging.md
  - Decorators: decorators.md
  - Python internals: internals.md
  - flask: flask.md


theme: 
  name: material